In [2]:
import sympy as sym

sym.init_printing()

x, y = sym.symbols("x, y")


solns = sym.solve(
        [-7*x + 5*y + 41,
         -2*x - 6*y + 40]
, [x, y])


In [3]:
solns

⎧   223     99⎫
⎨x: ───, y: ──⎬
⎩    26     26⎭

In [8]:
# Question 4
x, y = sym.symbols("x, y")
sym.solve(
        [-5*x + 6*y + 29,
         -2*x - 4*y - 14]
, [x, y])

{x: 1, y: -4}

In [12]:
# Question 5
x, y = sym.symbols("x, y")
sym.solve(
        [x*3.1 + y*2.5 - 3734.8,
         x + y - 1336]
, [x, y])

{x: 658.0, y: 678.0}

In [15]:
# Question 6
t, b = sym.symbols("t, b")
sym.solve([
    t + b - 4,
    150* t + 350*b - 1200
]
, [t, b])

{b: 3, t: 1}

In [17]:
# Question 7
S, L = sym.symbols("S, L")
sym.solve([
    20*S + 19*L - 453.5,
    17*S + 15*L - 366.5
]
, [S, L])

{L: 16.5, S: 7.0}

In [20]:
# Question 8
x,y,z = sym.symbols("x,y,z")
sym.solve([
    x + -2* + z + 3,
    y+2*z + 4,
    x+y+3*z + 7
]
, [x,y,z])

{x: -1, y: 0, z: -2}

In [56]:
# Question 9
x,y,z = sym.symbols("x,y,z")
sym.solve([
    x + y + z - 134,
    670*x +987*y + 1198*z - 116187,
    x - 2*y
]
, [x,y,z])
# TODO

{x: 70, y: 35, z: 29}

In [32]:
import numpy as np

blends = np.array([
    [.65, .60, .95], # Copper
    [.35, .40, .05], # Zinc
])

plants = np.array([
    [14000, 14000],
    [5000, 3000],
    [30000, 25000]
])

cost = np.array([
    [4.34], # copper
    [0.73] # zinc
])

np.dot(blends, plants)

array([[40600., 34650.],
       [ 8400.,  7350.]])

In [33]:
40600*4.34 + 8400 * 0.73

182336.0

In [34]:
34650*4.34 + 7350 * 0.73

155746.5

In [36]:
# Question 11
cars = np.array([
    [17000, 11000],
    [23000, 19000],
    [33000, 35000],
    [54000, 56000]
])
profits = np.array([
    [0.13, 0, 0, 0],
    [0, 0.11, 0, 0],
    [0, 0, 0.09, 0],
    [0, 0, 0, 0.22]
])

np.dot(profits, cars)

array([[ 2210.,  1430.],
       [ 2530.,  2090.],
       [ 2970.,  3150.],
       [11880., 12320.]])

In [37]:
12320 * 3

36960

In [45]:
# Question 12
from scipy.linalg import inv

m = [
    [5, -5],
    [-1, 3]
]

print("inverse is")
print(inv(m))

y = np.array(
    [2, -1]
)
# Mx = y
# M-1 * M * x = M-1 * y
# x = M-1 * y
np.dot(inv(m), y)

inverse is
[[0.3 0.5]
 [0.1 0.5]]


array([ 0.1, -0.3])

In [48]:
# Question 13
r,t,p = sym.symbols("r,t,p")
sym.solve([
    # Rice | Tofu | Pnts
    49*r   + 4*t  +  33*p - 217, # Carbs
    0*r    + 5*t  +  73*p - 244, # Fat
    5*r    + 15*t +  28*p - 169, # Protien
]
, [r,t,p])

{p: 3, r: 2, t: 5}

In [50]:
# Question 14
import numpy as np

# y = [-6, 18]

D = np.array([
    [-4, -2],
    [5, -1],
]) # D

Dx = np.array([
    [-6, -2],
    [18, -1],
]) # D x

Dy = np.array([
    [-4, -6],
    [5, 18],
]) # D y


print("|D| = ", np.linalg.det(D))
print("|D_x| = ", np.linalg.det(Dx))
print("|D_y| = ", np.linalg.det(Dy))
print("x = |D_x|/|D| = ", np.linalg.det(Dx)/np.linalg.det(D))
print("y = |D_y|/|D| = ", np.linalg.det(Dy)/np.linalg.det(D))


|D| =  13.999999999999996
|D_x| =  41.999999999999986
|D_y| =  -41.999999999999986
x = |D_x|/|D| =  2.9999999999999996
y = |D_y|/|D| =  -2.9999999999999996


In [52]:
# Question 15

# y = [40, 18, -24]

D = np.array([
    [6, 5, -5],
    [2, 3, -1],
    [1, -6, -2],
]) # D

Dx = np.array([
    [40, 5, -5],
    [18, 3, -1],
    [-24, -6, -2],
]) # D x

Dy = np.array([
    [6, 40, -5],
    [2, 18, -1],
    [1, -24, -2],
]) # D y

Dz = np.array([
    [6, 5, 40],
    [2, 3, 18],
    [1, -6, -24],
]) # D z

print("|D| = ", np.linalg.det(D))
print("|D_x| = ", np.linalg.det(Dx))
print("|D_y| = ", np.linalg.det(Dy))
print("|D_z| = ", np.linalg.det(Dz))
print("x = |D_x|/|D| = ", np.linalg.det(Dx)/np.linalg.det(D))
print("y = |D_y|/|D| = ", np.linalg.det(Dy)/np.linalg.det(D))
print("z = |D_z|/|D| = ", np.linalg.det(Dz)/np.linalg.det(D))

|D| =  17.99999999999999
|D_x| =  0.0
|D_y| =  90.0
|D_z| =  -53.999999999999986
x = |D_x|/|D| =  0.0
y = |D_y|/|D| =  5.000000000000003
z = |D_z|/|D| =  -3.000000000000001
